# Generated by Django 3.2.5 on 2021-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(blank=True, max_length=85, null=True)),
                ('Company_Address', models.TextField(blank=True, max_length=255, null=True)),
                ('Company_Phone_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Hotline_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Fax_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Email_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Website_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('Facebook_Link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Linkedin_Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Instagram_Link', models.CharField(blank=True, max_length=200, null=True)),
                ('Youtube_Link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
