# Generated by Django 3.2 on 2021-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
