# Generated by Django 3.2 on 2021-08-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_companyinformation_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Simage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
