# Generated by Django 3.2.5 on 2021-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_sliderm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSupport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Titel', models.CharField(blank=True, max_length=200, null=True)),
                ('Discription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
