# Generated by Django 3.2.5 on 2021-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_specialsupport_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Discription', models.TextField(blank=True, max_length=200, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon')),
            ],
        ),
    ]
