# Generated by Django 3.2.5 on 2021-08-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0010_classtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.classtype')),
            ],
        ),
    ]
