# Generated by Django 3.2.5 on 2021-08-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0011_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
