# Generated by Django 3.2.5 on 2021-08-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quatation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True)),
                ('Person', models.IntegerField(blank=True, null=True)),
                ('Sdate', models.DateField(blank=True, null=True)),
                ('Edate', models.DateField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Class_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.classtype')),
                ('TypeOf_Insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.typeofinsurance')),
            ],
        ),
    ]
