# Generated by Django 3.2.5 on 2021-08-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_quatation_stay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quatation',
            old_name='stay',
            new_name='stadate',
        ),
    ]
