# Generated by Django 3.2.5 on 2021-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0015_rename_stay_quatation_stadate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quatation',
            name='stadate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
