# Generated by Django 3.2.5 on 2021-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0019_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatation',
            name='customeryear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
