# Generated by Django 3.2.5 on 2021-08-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0020_quatation_customeryear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Coustomer_Year', models.CharField(blank=True, max_length=255, null=True)),
                ('Stay_Days', models.CharField(blank=True, max_length=255, null=True)),
                ('net', models.IntegerField()),
                ('Vat', models.IntegerField()),
                ('Gross', models.IntegerField()),
                ('Class_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.classtype')),
                ('TypeInsurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='software.typeofinsurance')),
            ],
        ),
    ]
