# Generated by Django 3.2.5 on 2021-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0021_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Coustomer_Year',
            new_name='Coustomer_Year_End',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='Stay_Days',
            new_name='Coustomer_Year_Start',
        ),
        migrations.AddField(
            model_name='rate',
            name='Stay_Days_End',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='Stay_Days_Start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
