# Generated by Django 3.2.5 on 2021-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0023_auto_20210817_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Coustomer_Year_Start',
            field=models.FloatField(default=True),
        ),
    ]
