# Generated by Django 3.2.5 on 2021-08-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0024_alter_rate_coustomer_year_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Coustomer_Year_Start',
            field=models.IntegerField(default=True),
        ),
    ]
