# Generated by Django 3.2.5 on 2021-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0025_alter_rate_coustomer_year_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatation',
            name='Net',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
