# Generated by Django 3.2.5 on 2021-08-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0026_quatation_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatation',
            name='Gross',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quatation',
            name='Vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
