# Generated by Django 3.2.5 on 2021-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0027_auto_20210818_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Coustomer_Year_Start',
            field=models.FloatField(default=True),
        ),
    ]
