# Generated by Django 3.2.5 on 2021-08-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0029_additionalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='issue',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
