# Generated by Django 3.2.5 on 2021-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0030_additionalinformation_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='Bkash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
